
url: "https://julien.adamarie.pro"
baseurl: ""

title: ./julien -adam --marie
description: "A good {{ placeholder }} is always learning..."

email: julien@adamarie.pro
github_username:  gweodoo
google_analytics: UA-28586663-2
timezone: "Europe/Paris"
highlighter: rouge

# Build settings
source: .
destination: ./_site
layouts_dir: ./_layouts
markdown: kramdown
markdown_ext: "md,markdown"
theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links

exclude:
   - Gemfile
   - Gemfile.lock
   - LICENSE
